# Generated by Django 4.2.2 on 2023-06-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_login', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа')),
                ('do', models.CharField(default='', max_length=100, verbose_name='Действие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'лог авторизации',
                'verbose_name_plural': 'Логи авторизаций',
            },
        ),
    ]
