# Generated by Django 4.2.2 on 2023-06-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_logsinvites'),
        ('logs', '0002_logauthuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauthuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.corporations', verbose_name='компания'),
        ),
    ]
