# Generated by Django 4.2.2 on 2023-06-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_logsinvites'),
        ('logs', '0003_logauthuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauthuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.corporations', verbose_name='компания'),
        ),
    ]
