# Generated by Django 4.2.2 on 2023-06-18 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporations',
            name='directors',
        ),
        migrations.AddField(
            model_name='corporations',
            name='directors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
