# Generated by Django 4.2.2 on 2023-06-19 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporations',
            name='directors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='logo',
            field=models.ImageField(upload_to='main/corporation/logos', verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main/users/avatars/default.webp', upload_to='main/users/avatars'),
        ),
    ]
