# Generated by Django 4.2.2 on 2023-06-19 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_corporations_directors_alter_corporations_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporations',
            name='directors',
        ),
        migrations.AddField(
            model_name='corporations',
            name='directors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
