# Generated by Django 4.2.2 on 2023-06-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_corporations_directors_corporations_directors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код приглашения')),
                ('activations', models.IntegerField(verbose_name='Количество активаций')),
                ('max_activations', models.IntegerField(verbose_name='Максимальное количество активаций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_invite', models.DateTimeField(auto_now=True, verbose_name='Время последнего присоеденения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corporations', verbose_name='Компания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
    ]
