# Generated by Django 4.2.2 on 2023-06-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_compinvites_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.corporations'),
        ),
    ]
