# Generated by Django 4.2.2 on 2023-06-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_corporation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код приглашения')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.corporations', verbose_name='компания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'лог приглашения',
                'verbose_name_plural': 'Логи приглашений',
            },
        ),
    ]
