# Generated by Django 4.2.2 on 2023-06-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_logsinvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsinvites',
            name='do',
            field=models.TextField(default='', max_length=300, verbose_name='Действие'),
        ),
    ]
