# Generated by Django 4.2.2 on 2023-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logsinvites_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinvites',
            name='activations',
            field=models.IntegerField(default=0, verbose_name='Количество активаций'),
        ),
    ]
