# Generated by Django 4.2.2 on 2023-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_compinvites_activations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP последнего входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при регистрации'),
        ),
    ]
