# Generated by Django 4.2.2 on 2023-06-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_last_ip_user_reg_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.corporations'),
        ),
    ]
