# Generated by Django 4.2.2 on 2023-06-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_corporation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogsInvites',
        ),
    ]
