# Generated by Django 4.2.2 on 2023-07-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_logsinvites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Задача')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поручения')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.corporations', verbose_name='Компания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Поручитель')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worker', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
