# Generated by Django 4.2.2 on 2023-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'задачу  ', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новая'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('done', 'Выполнено'), ('in_process', 'В процессе'), ('in_start', 'Не начат')], default='in_start', max_length=50),
        ),
    ]
