# Generated by Django 4.2.2 on 2023-07-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_messages_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='text',
        ),
    ]
